#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__root="$(cd "$(dirname "${__dir}")"/../ && pwd)"

cd "$__root"

# Install uv
curl -LsSf https://astral.sh/uv/install.sh | sh
source "$HOME/.local/bin/env"

# Install dependencies
uv python install "$PYTHON_VERSION"
uv sync --all-extras

# Run pylint
uv run pylint src/
